# Generated by Django 6.0.6 on 2026-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
