# Generated by Django 6.0.6 on 2026-07-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_task_categories'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
    ]
